PIC 	EQU 20H
TIMER 	EQU 10H
N_F10	EQU 10
N_CLK	EQU 11

	ORG 40
IP_F10	DW RUT_F10
	
	ORG 44
IP_CLK	DW RUT_CLK
	
	ORG 1000H
SEG	DB 036H
	DB 039H
FIN	DB ?
MSJ	DB "INGRESE UN VALOR:"
FIN_M	DB ?

	ORG 3000H
RUT_F10:PUSH AX
	MOV AL, 11111100B
	OUT PIC+1, AL ;IMR=11111100B
	MOV AL, 20H
	OUT PIC,AL
	POP AX
	IRET
	
	ORG 3500H
RUT_CLK:PUSH AX
	INT 7
	DEC SEG+1
	CMP SEG+1, 30H
	JNZ RESET
	INT 7
	MOV SEG+1, 39H
	DEC SEG		
RESET: 	MOV AL,0
	OUT TIMER,AL
	MOV AL, 20H
	OUT PIC,AL
	POP AX
	IRET

	ORG 2000H
	CLI
	MOV AL, 11111110B
	OUT PIC+1, AL ;IMR=11111110B ;PRIMERO SOLO HABILITO LA INT F10
	MOV AL, N_F10
	OUT PIC+4, AL ;INT0=10
	MOV AL, N_CLK
	OUT PIC+5, AL ;INT1=11
	MOV AL, 0
	OUT TIMER, AL ;CONT=0
	MOV AL, 1
	OUT TIMER+1,AL ;COMP=1
	MOV BX, OFFSET MSJ
	MOV AL, OFFSET FIN_M-OFFSET MSJ
	INT 7			;PARA IMPRIMIR EL MENSAJE AL USUARIO
	MOV BX, OFFSET SEG		;HABRUA QUE LEER EL VALOR INICIAL DEL CONTADOR (NO SE PUEDE DE DOS DIGITOS)
	MOV AL, OFFSET FIN-OFFSET SEG 	;PARA MOSTRAR LOS SEGUNDOS EN PANTALLA (BX EN [SEG] YA ESTA CONFIGURADO)
	STI
LAZO:	CMP SEG, 2FH ;2FH=CARACTER ANTERIOR AL 0 EN ASCII
	JZ TERMINAR
	JMP LAZO
TERMINAR:HLT
	END
