	ORG 1000H
LETRA	DB 41H			;41H=LETRA A MAYUSCULA
	
	ORG 2000H
	MOV AL,1
LAZO:	MOV BX,OFFSET LETRA
	INT 7 			;IMPRIMIR LETRA MAYUSCULA
	ADD LETRA, 20H 		;AVANZAR A LA LETRA MINUSCULA
	MOV BX, OFFSET LETRA
	INT 7 			;IMPRIMIR LETRA MINUSCULA
	SUB LETRA,20H		;VOLVER A LA LETRA MAYUSCULA
	INC LETRA 		;PASAR A LA SIGUIENTE LETRA
	CMP LETRA,5BH 		;5AH=Z --> 5BH=CARACTER SIGUIENTE A LA Z (NO IMPRIMIR)
	JZ FIN
	JMP LAZO
FIN:	HLT
	END
 