	ORG 1000H
MSJ1	DB "NUMERO 1:"
FIN1 	DB ?
MSJ2	DB "NUMERO 2:"
FIN2	DB ?
MSJ3	DB "RESULTADO:"
FIN3	DB ?
NUM1	DB ?
NUM2	DB ?
RES	DB ?
UNO	DB "1"

	ORG 2000H
	;PEDIR, GUARDAR Y MOSTRAR EL PRIMER NUMERO:
	MOV BX, OFFSET MSJ1
	MOV AL, OFFSET FIN1-OFFSET MSJ1
	INT 7
	MOV BX, OFFSET NUM1
	INT 6
	MOV AL,1
	INT 7

	;PEDIR, GUARDAR Y MOSTRAR EL SEGUNDO NUMERO:
	MOV BX, OFFSET MSJ2
	MOV AL, OFFSET FIN2-OFFSET MSJ2
	INT 7
	MOV BX, OFFSET NUM2
	INT 6
	MOV AL,1
	INT 7
	
	;OBTENER EL NUMERO DECIMAL A PARTIR DEL CODIGO DEL CARACTER QUE REPRESENTA
	MOV CL, NUM1
	MOV CH, NUM2
	SUB CL,30H
	SUB CH,30H

	;REALIZAR LA SUMA E IMPRIMIR EL RESULTADO, SEGUN SEA DE UNO O DOS DIGITOS
	ADD CL, CH
	MOV BX, OFFSET MSJ3
	MOV AL, OFFSET FIN3-OFFSET MSJ3
	INT 7
	CMP CL,10
	JS UN_DIGITO
	;EL NUMERO ES DE 2 DIGITOS (<18):
	;IMPRIMO LA DECENA (EL "1")
	MOV BX, OFFSET UNO
	MOV AL,1
	INT 7
	SUB CL,10 ;OBTENGO LA UNIDAD
	;IMPRIMO LA UNIDAD:
UN_DIGITO:MOV RES, CL
	ADD RES,30H
	MOV BX, OFFSET RES
	MOV AL,1
	INT 7
	HLT
	END
