;ESTA SIN TERMINAR	
ORG 1000H
MSJ1	DB "NUMERO 1:"
FIN1 	DB ?
MSJ2	DB "NUMERO 2:"
FIN2	DB ?
MSJ3	DB "RESULTADO:"
FIN3	DB ?
NUM1	DB ?
NUM2	DB ?
RES	DB ?

	ORG 2000H
	;PEDIR, GUARDAR Y MOSTRAR EL PRIMER NUMERO:
	MOV BX, OFFSET MSJ1
	MOV AL, OFFSET FIN1-OFFSET MSJ1
	INT 7
	MOV BX, OFFSET NUM1
	INT 6
	MOV AL,1
	INT 7

	;PEDIR, GUARDAR Y MOSTRAR EL SEGUNDO NUMERO:
	MOV BX, OFFSET MSJ2
	MOV AL, OFFSET FIN2-OFFSET MSJ2
	INT 7
	MOV BX, OFFSET NUM2
	INT 6
	MOV AL,1
	INT 7
	
	;OBTENER EL NUMERO DECIMAL A PARTIR DEL CODIGO DEL CARACTER QUE REPRESENTA
	MOV CL, NUM1
	MOV CH, NUM2
	SUB CL,30H
	SUB CH,30H

	;REALIZAR LA RESTA	
	SUB CL, CH
	JS 
	MOV BX, OFFSET MSJ3
	MOV AL, OFFSET FIN3-OFFSET MSJ3
	INT 7
	