	ORG 1000H
MSJ	DB "INGRESE LA CLAVE"
FIN	DB ?
MSJ1	DB "ACCESO PERMITIDO"
FIN1	DB ?
MSJ2	DB "ACCESO DENEGADO"
FIN2	DB
PRED	DB "ABCD"
CLAVE	DB ?
	
	ORG 3000H
VALIDAR: MOV DL, [BX]
	MOV DH, OFFSET C
	CMP DL, 
	ORG 2000H
	MOV BX, OFFSET MSJ
	MOV AL, OFFSET FIN1-OFFSET MSJ
	INT 7
	MOV BX, OFFSET CLAVE
	INT 6
	MOV BX, OFFSET PRED
	CALL VALIDAR