	ORG 1000H 
TABLA 	DB DUP(2,4,6,8,10,12,14,16,18,20)
FIN 	DB ?
TOTAL 	DB ?
MAX 	DB 13
	ORG 2000H
	MOV AL,0 ;INICIALIZO EL CONTADOR
	MOV CL, OFFSET FIN-OFFSET TABLA
	MOV BX, OFFSET TABLA
	MOV DL,MAX
BUCLE: 	CMP DL, [BX] ; DL-[BX]= 13-2=11 la 1ra vez
	JS PROXIMO  ; SI EL RESULTADO ES NEGATIVO (EL ELEMENTO DE LA TABLA ES MAYOR QUE MAX) PASAR AL SIGUIENTE ELEMENTO
	INC AL ; SI ES MENOR O IGUAL INCREMENTAR EL CONTADOR
PROXIMO:INC BX
	DEC CL
	JNZ BUCLE
	MOV TOTAL,AL
	HLT
	END
